# Generated by Django 4.0.2 on 2022-05-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0003_alter_triggers_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenaries',
            name='slug',
        ),
    ]
