# Generated by Django 4.0.2 on 2022-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0004_remove_scenaries_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='title',
        ),
        migrations.AddField(
            model_name='triggers',
            name='desc',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
