# Generated by Django 4.0.2 on 2022-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0005_remove_audio_title_triggers_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggers',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
