# Generated by Django 4.0.2 on 2022-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0006_alter_triggers_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenaries',
            name='combo_triggers',
            field=models.ManyToManyField(to='autodj.ComboTrigger'),
        ),
    ]
